### ISSUE TITLE
GitHub Enterprise Server compatibility

### ISSUE THREAD

**Issue by thewismit** [zyborg/pester-tests-report#2]
Hello, do you have a GitHub Enterprise server version of the pester-tests-report action?
Thank you!

**Comment by ebekker** [comment]
Sorry, I don't have access to GH Enterprise, so I don't know if or how it would work with it.  I assume you have already tried to use it and it didn't work for you?

Does GHE support GitHub Workflow/Actions?

**Comment by ebekker** [comment]
According to this little blurb from [here](https://docs.github.com/en/actions/getting-started-with-github-actions/about-github-actions):

> GitHub Actions is available with GitHub Free, GitHub Pro, GitHub Free for organizations, GitHub Team, GitHub Enterprise Cloud, and GitHub One. GitHub Actions is not available for private repositories owned by accounts using legacy per-repository plans. For more information, see "[GitHub's products](https://docs.github.com/articles/github-s-products)."

So looks like GHE Server (aka self-hosted) does not support Actions.

**Comment by thewismit** [comment]
Thanks for getting back to me. That’s disappointing.   From: Eugene BekkerSent: Thursday, September 3, 2020 3:52 PMTo: zyborg/pester-tests-reportCc: Will Smith; AuthorSubject: Re: [zyborg/pester-tests-report] GitHub Enterprise Server compatibility (#2) 
According to this little blurb from here:

GitHub Actions is available with GitHub Free, GitHub Pro, GitHub Free for organizations, GitHub Team, GitHub Enterprise Cloud, and GitHub One. GitHub Actions is not available for private repositories owned by accounts using legacy per-repository plans. For more information, see "GitHub's products."

So looks like GHE Server (aka self-hosted) does not support Actions.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/zyborg/pester-tests-report/issues/2#issuecomment-686720801",
"url": "https://github.com/zyborg/pester-tests-report/issues/2#issuecomment-686720801",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
