### ISSUE TITLE
Problem producing test results in Git Actions - 65K limit on Check Run API

### ISSUE THREAD

**Issue by MattBishop13** [zyborg/pester-tests-report#5]
Hello,

In attempting to use this repo tp  produce test results in git actions I run into the below error.  During running Pester 5.1.1 tests against the test scripts I was able to received no errors as the script passed the pester tests. What other information would you need to be able to look further into this?

![image](https://user-images.githubusercontent.com/49490739/104461738-b91eab80-557d-11eb-886c-976af00bee52.png)

**Comment by ebekker** [comment]
Unfortunately, you have run into the 65K limitation on GitHub's Check Run API.

This is the API that's used to "attach" artifacts to the GitHub Workflow, like the test report.  This API was not really intended to attach such large artifacts as formatted reports, mostly for alerting to one-off issues in compiles and tests.

However, an alternative is to use _Gist-based_ reports.  What you can do is disable the Check Run based reports by enabling the [**`skip_check_run`**](https://github.com/zyborg/pester-tests-report/blob/2322868ada4142e748f0b18455cbe164f7819356/action.yml#L94) flag, and then enabling Gist-based reports using the [**`gist_name`**](https://github.com/zyborg/pester-tests-report/blob/2322868ada4142e748f0b18455cbe164f7819356/action.yml#L101) and [**`gist_token`**](https://github.com/zyborg/pester-tests-report/blob/2322868ada4142e748f0b18455cbe164f7819356/action.yml#L126) inputs.

This is generally a better approach as gists have a virtually unlimited size so can handle reports with as many tests as you can throw at it, and it can optionally produce badges that you can use to reflect that state of your tests, such as these in the [sample](https://github.com/zyborg/pester-tests-report#samples).

**Comment by ebekker** [comment]
There is the same problem with the similar [GitHub Action for .NET Test Reports](https://github.com/zyborg/dotnet-tests-report) and you can read some more about it in [this issue](https://github.com/zyborg/dotnet-tests-report/issues/9).

I'll close this issue for now, but if you have any more questions, feel free to keep the discussion going.

**Comment by ebekker** [comment]
I'll also link to [this issue](https://github.com/github/docs/issues/2403) for the GitHub Docs related to documentation of this limit.

**Comment by ebekker** [comment]
Looks like this issue is now tracked in [this issue](https://github.com/github/docs/issues/3765).
