### ISSUE TITLE
Parameter output_level incorrectly handled

### ISSUE THREAD

**Issue by danubie** [zyborg/pester-tests-report#7]
Hi,
thanks for creating this neat action. While tracking done an issue in using it, I discovered, that the pester parameter "output_level" is not handled correctly. If you pass a (correct) value, this does not get passed to the pester call.

```
[-] Context blabla: .
 RuntimeException: Unsupported level out output ''
```

I will provide you a fix.
thx and regards,
Wolfgang

**Comment by ebekker** [comment]
Done! v1.4.0
